[package]
name = "kernel-qemu"
version = "0.1.0"
edition = "2021"

[features]
ram-block-device = []
qemu-boot-smoke = []
qemu-virtio-blk-smoke = []
qemu-mm-selftest = []
qemu-fs-selftest = []
qemu-proc-selftest = []
qemu-sched-selftest = []
qemu-sync-selftest = []
qemu-checkpoint-selftest = []
qemu-selftest = [
    "qemu-boot-smoke",
    "qemu-mm-selftest",
    "qemu-fs-selftest",
    "qemu-sched-selftest",
    "qemu-sync-selftest",
    "qemu-proc-selftest",
    "qemu-checkpoint-selftest",
]

[dependencies]
virtio-drivers = { version = "=0.13.0", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
